import React, { useState, useEffect} from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import ChatList from '../public/components/ChatListItem'
import ChatIntro from '../public/components/ChatIntro'
import ChatWindow from '../public/components/ChatWindow'

import DonutLargeIcon from '@material-ui/icons/DonutLarge'
import ChatIcon from '@material-ui/icons/Chat'
import MoreVertIcon from '@material-ui/icons/MoreVert'
import SearchIcon from '@material-ui/icons/Search'

export default function Home() {

  const [chatlist, setChatList] = useState([
    {chatId: 1, title:'Marlon Dener', image:'https://www.w3schools.com/howto/img_avatar2.png'},
    {chatId: 2, title:'Dener', image:'https://www.w3schools.com/howto/img_avatar2.png'},
    {chatId: 3, title:'Michael Bastos', image:'https://www.w3schools.com/howto/img_avatar2.png'},
    {chatId: 4, title:'Marcio Souza', image:'https://www.w3schools.com/howto/img_avatar2.png'}
]);
  const [activeChat, setActiveChat] = useState({});

  return (
    <div className={styles.container}>
      <Head>
        <title>Whatsapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.app_window}>
          <div className={styles.sidebar}>

            <header className={styles.header}>
                
                 <img className={styles.header_avatar} src="https://www.w3schools.com/howto/img_avatar2.png" alt="" />

                 <div className={styles.header_buttons}>
                   <div className={styles.header_btn}>
                      <DonutLargeIcon style={{color:'#919191'}} />
                      <ChatIcon className={styles.space_icon} style={{color:'#919191'}} />
                      <MoreVertIcon style={{color:'#919191'}} />
                   </div>
                 </div>

            </header>
            
               <div className={styles.search}>
                    <div className={styles.search_input}>
                        <SearchIcon fontSize="small" style={{color:'#919191'}} />
                        <input type="search" placeholder="Procurar ou começar uma nova conversa" />
                    </div>
               </div>

               <div className={styles.chatlist}>
                    {chatlist.map((item, key) =>(
                        <ChatList 
                          key={key}
                          active={activeChat.chatId === chatlist[key].chatId}
                          onClick={()=>setActiveChat(chatlist[key])}
                        
                        />
                    ))} 
                 
                </div> 

          </div>
           {/* Starting part to message*/}             
          <div className={styles.contentArea}>
            {activeChat.chatId !== undefined &&
            <ChatWindow />
            }
            {activeChat.chatId == undefined &&
            <ChatIntro />
            }
          </div>
      </main>
    </div>
  )
}
