import React, { useState, useEffect} from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import ApiFirebase from '../src/ApiFirebase'

import Login from '../public/components/Login'
import ChatList from '../public/components/ChatListItem'
import ChatIntro from '../public/components/ChatIntro'
import ChatWindow from '../public/components/ChatWindow'
import NewChat from '../public/components/NewChat'

import DonutLargeIcon from '@material-ui/icons/DonutLarge'
import ChatIcon from '@material-ui/icons/Chat'
import MoreVertIcon from '@material-ui/icons/MoreVert'
import SearchIcon from '@material-ui/icons/Search'

export default function Home() {

  const [chatlist, setChatList] = useState([]);
  const [activeChat, setActiveChat] = useState({});
  const [user, setUser] = useState({
    id:'TOFsn9iFbOYFSfdVjIfA8WgwCmm1',
    name:'marlon',
    avatar:'https://graph.facebook.com/3761201050672731/picture'
  })
  const [showNewChat, setShowNewChat] = useState(false);

  const openNewChat = () =>{
    setShowNewChat(true);
  }

  const VoltarInfoDoUserLogado = async (u) =>{
    let newUser = {
      id:u.uid,
      name:u.displayName,
      avatar: u.photoURL
    };

    await ApiFirebase.addUser(newUser);

    setUser(newUser);
  }

  if(user == null){
      return (<Login onReceive={VoltarInfoDoUserLogado} />)
  }

  useEffect(() =>{
    if(user !== null){
      let unsub = ApiFirebase.onChatList(user.id, setChatList);
      return unsub;
    } 
  }, [user]);


  return (
    <div className={styles.container}>
      <Head>
        <title>Whatsapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.app_window}>
          <div className={styles.sidebar}>

            <NewChat 
             chatlist={chatlist}
             user={user}
             show={showNewChat}
             setShow={setShowNewChat} 
            />

            <header className={styles.header}>
                
                 <img className={styles.header_avatar} src={user.avatar} alt="" />

                 <div className={styles.header_buttons}>
                   <div className={styles.header_btn}>
                      <DonutLargeIcon style={{color:'#919191'}} />
                      <ChatIcon className={styles.space_icon} style={{color:'#919191'}}
                       
                       onClick={openNewChat}

                      />
                      <MoreVertIcon style={{color:'#919191'}} />
                   </div>
                 </div>

            </header>
            
               <div className={styles.search}>
                    <div className={styles.search_input}>
                        <SearchIcon fontSize="small" style={{color:'#919191'}} />
                        <input type="search" placeholder="Procurar ou começar uma nova conversa" />
                    </div>
               </div>

               <div className={styles.chatlist}>
                    {chatlist.map((item, key) =>(
                        <ChatList 
                          key={key}
                          data={item}
                          active={activeChat.chatId === chatlist[key].chatId}
                          onClick={()=>setActiveChat(chatlist[key])}
                        
                        />
                    ))} 
                 
                </div> 

          </div>
           {/* Starting part to message*/}             
          <div className={styles.contentArea}>
            {activeChat.chatId !== undefined &&
            <ChatWindow 
             user={user}
             data={activeChat} 
            />
            }
            {activeChat.chatId == undefined &&
            <ChatIntro />
            }
          </div>
      </main>
    </div>
  )
}
